language: c

script: "./travis-tool.sh run_tests"

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - sudo add-apt-repository -y ppa:edd/misc
  - sudo apt-get update -qq
  - sudo apt-get install -y libv8-dev
  - sudo apt-get install -y gdal-bin libgdal-dev libgdal1-dev netcdf-bin libproj-dev libgdal1h
  - "./travis-tool.sh bootstrap"
  - "./travis-tool.sh install_deps"
  - "./travis-tool.sh r_binary_install rgdal"
  - "./travis-tool.sh github_package jimhester/covr"

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
  slack:
    secure: F3ywEGAskqvJ6BlCXZgGPjUZkeSN+KRFbHpgKvVaMcf1nSMDfMSDS7X4rgGLLzHMu5lPbu/G69Hw7ousXFiO+b0cWShQcAK6xDYBGXs2MqmQLws3iFFnUKMjHQVwBpTcMPitsqU8gR27xWnC+Du5jzJ7amAO54LxfK3BPHm7cDg=
