on: [push, pull_request]

name: R-CMD-check-docker

jobs:
  R-CMD-check-docker:
    runs-on: ubuntu-latest
    
    name: ${{ matrix.config.image }}

    strategy:
      fail-fast: false
      matrix:
        config:
        - {image: "jakubnowosad/rspatial_proj6"}
        - {image: "rocker/r-devel"}
        
    container: ${{ matrix.config.image }}
    
    steps:
      - uses: actions/checkout@v1
      
      - name: Install system dependencies
        if: contains(matrix.config.image('rocker/r-devel'))
        run: |
          sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
          sudo apt-get -y update
          sudo apt-get -y install libgdal-dev gdal-bin libgeos-dev \
          libgeos++-dev git-core pandoc pandoc-citeproc libproj-dev libjq-dev \
          libudunits2-dev libcurl4-openssl-dev libssl-dev libprotobuf-dev \
          protobuf-compiler libprotoc-dev valgrind libpq-dev netcdf-bin \
          libnode-dev

      - name: Install dependencies
        run: Rscript -e "install.packages('remotes')" -e "remotes::install_deps(dependencies = TRUE)" -e "remotes::install_cran('rcmdcheck')"

      - name: Check
        run: Rscript -e "rcmdcheck::rcmdcheck(args = c('--no-manual', '--as-cran'), error_on = 'warning', check_dir = 'check')"

      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@master
        with:
          name: ${{ runner.os }}-${{ matrix.config.image}}
          path: check
